on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt update && sudo apt install cmake
      - run: cmake -B build
      - run: cmake --build build
      - run: ctest --test-dir build
